# Site settings
title: Ral Oliver - Frontend Developer
email: contato@raloliver.com.br
description: > 
  Apaixonado pela Valesca, pai da Laura e amo escrever... principalmente se for código.
  Gratidão, Honestidade, Disciplina, Coerência e Criatividade. Esses são os meus principais valores.
baseurl: "/jekyll-blog"
url: "https://raloliver.github.io" 
twitter_username: raloliver
github_username:  raloliver

# Build settings
markdown: kramdown
permalink: /:title

#page_gen
page_gen:
  - data: 'posts'
    template: 'article'
    name: 'url'
    dir: ''
    extension: 'html'
